@startuml 有nginx 时的部署图
node f5
node n1 {
    cloud apisix1
    component nginx1
    component java_blue_1
    component java_blue_2

}
node n2 {
    cloud apisix2
     component nginx2
    component java_blue__1
    component java_blue__2

}
node n3_green{
    cloud apisix3
     component nginx3
    component java_green_1
    component java_green_2
}
f5-->apisix1
f5-->apisix2
f5-->apisix3
apisix1->nginx1
apisix1->nginx2
apisix1->nginx3





@enduml