services:
  broker1:
    image: apache/rocketmq:5.3.1
    container_name: broker1
    hostname: broker1
    depends_on:
    - namesrv1
    - namesrv2
    - namesrv3
    networks:
    - rocketmq
    command: sh mqbroker -c /etc/broker.properties
    volumes:
    - ./config/broker.properties:/etc/broker.properties
    - ./data/broker1:/home/rocketmq/store
  broker2:
    image: apache/rocketmq:5.3.1
    container_name: broker2
    hostname: broker2
    depends_on:
    - namesrv1
    - namesrv2
    - namesrv3
    networks:
    - rocketmq
    command: sh mqbroker -c /etc/broker.properties
    volumes:
    - ./config/broker.properties:/etc/broker.properties
    - ./data/broker2:/home/rocketmq/store

  broker3:
    image: apache/rocketmq:5.3.1
    container_name: broker3
    hostname: broker3
    depends_on:
    - namesrv1
    - namesrv2
    - namesrv3
    networks:
    - rocketmq
    command: sh mqbroker -c /etc/broker.properties
    volumes:
    - ./config/broker.properties:/etc/broker.properties
    - ./data/broker3:/home/rocketmq/store